In [78]:
import torch
import numpy as np
import pandas as pd

In [79]:
scalar = torch.tensor([15])
type(scalar.item())

int

In [80]:
scalar.ndim

1

In [81]:
vector = torch.tensor([1,2,3,4])

In [82]:
vector.ndim

1

In [83]:
vector.shape

torch.Size([4])

In [84]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6]])

In [85]:
matrix.ndim

2

In [86]:
matrix.shape

torch.Size([2, 3])

In [87]:
tensor = torch.tensor([[[1,2,3,4],
                        [5,6,7,8]]])

In [88]:
tensor.ndim

3

In [89]:
tensor.shape

torch.Size([1, 2, 4])

In [90]:
tensor4d = torch.tensor([[[1,2,3],
                          [4,5,6],
                          [7,8,9],
                          [10,11,12]],
                         [[1,2,3],
                          [4,5,6],
                          [7,8,9],
                          [10,11,12]],
                         [[1,2,3],
                          [3,4,5],
                          [4,5,6],
                          [5,6,7]]])

In [91]:
tensor4d.ndim

3

In [92]:
tensor4d.shape

torch.Size([3, 4, 3])

In [93]:
x = torch.tensor([[[[1,2,3,4]],[[5,6,7,8]]],
                  [[[1,2,3,4]],[[1,2,3,4]]],
                  [[[1,2,3,4]],
                   [[1,2,3,4]]]])

In [94]:
x.ndim

4

In [95]:
x.shape

torch.Size([3, 2, 1, 4])

`Random Tensors`

In [96]:
random_tensor = torch.rand((3,4))

In [97]:
random_tensor

tensor([[0.7041, 0.5573, 0.6959, 0.9849],
        [0.2924, 0.4823, 0.6150, 0.4967],
        [0.4521, 0.0575, 0.0687, 0.0501]])

In [98]:
example_image = torch.rand((224,224,3))

In [99]:
example_image

tensor([[[0.0108, 0.0343, 0.1212],
         [0.0490, 0.0310, 0.7192],
         [0.8067, 0.8379, 0.7694],
         ...,
         [0.6748, 0.8060, 0.4750],
         [0.0800, 0.0324, 0.7166],
         [0.9909, 0.1717, 0.2111]],

        [[0.6824, 0.7232, 0.5315],
         [0.3566, 0.8587, 0.5210],
         [0.7411, 0.7348, 0.7846],
         ...,
         [0.6347, 0.2333, 0.4229],
         [0.8224, 0.1978, 0.7320],
         [0.3527, 0.2636, 0.5240]],

        [[0.0839, 0.9054, 0.0632],
         [0.4952, 0.2441, 0.4634],
         [0.0765, 0.1611, 0.2216],
         ...,
         [0.3528, 0.6076, 0.7695],
         [0.4007, 0.9217, 0.2825],
         [0.6284, 0.1649, 0.6897]],

        ...,

        [[0.5480, 0.0853, 0.8401],
         [0.8561, 0.2798, 0.9670],
         [0.8160, 0.0725, 0.0900],
         ...,
         [0.3216, 0.3374, 0.4751],
         [0.6108, 0.9917, 0.7020],
         [0.3878, 0.2955, 0.8880]],

        [[0.2077, 0.8828, 0.7875],
         [0.6398, 0.2667, 0.9978],
         [0.

In [100]:
zeros = torch.zeros_like(random_tensor)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [101]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
torch.__version__

'2.4.0+cu121'

In [103]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [105]:
float_16tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [106]:
float_64tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float64)
float_64tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [107]:
float_16tensor * float_64tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

## Getting information from tensors

1. Tensors not right datatype - to get datatype, use `tensor.dtype`
2. Tensors not right shape - to get datatype, use `tensor.shape`
3. Tensors not right device - to get datatype, use `tensor.device`

In [108]:
some_tensor = torch.rand(3,4,dtype=torch.float64)
some_tensor

tensor([[0.5451, 0.5199, 0.8643, 0.6025],
        [0.7495, 0.4525, 0.5947, 0.7814],
        [0.3177, 0.6185, 0.7505, 0.5594]], dtype=torch.float64)

In [109]:
some_tensor.device, some_tensor.dtype, some_tensor.shape

(device(type='cpu'), torch.float64, torch.Size([3, 4]))

## Manipulating tensors

In [110]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [111]:
tensor * 10

tensor([10, 20, 30])

In [112]:
tensor - 10

tensor([-9, -8, -7])

In [113]:
# pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [114]:
tensor

tensor([1, 2, 3])

## Multiplication

In [115]:
## Element wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [116]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [117]:
tensor_A = torch.tensor([[4,3,5],
                         [8,2,9],
                         [1,5,2]])
tensor_B = torch.tensor([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

In [118]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 25,  61,  97],
        [ 39,  96, 153],
        [ 17,  41,  65]])

## Tensor Aggregation

In [119]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [120]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [121]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [122]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [123]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [124]:
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [125]:
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

## Reshaping, stacking, viewing, squeeze/unsqueeze, etc

In [126]:
# reshaping
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [127]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [128]:
# changing the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [129]:
# changing z changes x because a view shared the same memory as the original tensor
z[0,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [130]:
# stacking tensors
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [131]:
# squeeze and unsqueeze
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [132]:
x_reshaped.squeeze().shape

torch.Size([9])

In [133]:
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [134]:
# unsqueeze - adds a dimension to the specified dimension
x_reshaped.unsqueeze(dim=0)

tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [135]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x = torch.randint(1,16,(2,3,5))
x

tensor([[[ 8, 11,  6,  4,  1],
         [ 8, 11,  5,  3, 13],
         [15, 11,  6,  8,  4]],

        [[11, 10, 13,  5,  5],
         [14,  3, 13, 10, 11],
         [ 1,  9, 15,  8,  4]]])

In [136]:
torch.permute(x,(2,0,1))

tensor([[[ 8,  8, 15],
         [11, 14,  1]],

        [[11, 11, 11],
         [10,  3,  9]],

        [[ 6,  5,  6],
         [13, 13, 15]],

        [[ 4,  3,  8],
         [ 5, 10,  8]],

        [[ 1, 13,  4],
         [ 5, 11,  4]]])

In [137]:
# example
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [138]:
x_original[4,6,1] = 0.6969

In [139]:
x_permuted[1,4,6]

tensor(0.6969)

## Indexing

In [140]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [141]:
x[0,1,2], x[0][1][2]

(tensor(6), tensor(6))

In [142]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [143]:
x[:, 1, 1]

tensor([5])

## Pytorch and numpy

In [144]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [145]:
tensor.type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [146]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [147]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [148]:
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)
print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.6559, 0.1746, 0.9535, 0.2025],
        [0.7919, 0.6144, 0.4007, 0.8906],
        [0.2995, 0.6521, 0.3515, 0.6887]])
tensor([[0.6345, 0.4314, 0.6334, 0.0131],
        [0.4737, 0.6558, 0.6812, 0.2280],
        [0.4670, 0.8602, 0.9358, 0.4528]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [149]:
RANDOM_SEED = 10
torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(3,4)

print(tensor_C)
print(tensor_D)
print(tensor_C == tensor_D)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])
tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## GPU

In [150]:
!nvidia-smi

Thu Sep 12 17:12:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [151]:
torch.cuda.is_available()

True

In [152]:
# device agnostic code
device = "cuda" if torch.cuda.is_available()  else "cpu"
device

'cuda'

In [153]:
torch.cuda.device_count()

1

## Putting tensors and models on GPU

In [154]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [155]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [157]:
# moving tensors back to the cpu
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [158]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')